apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: server-v1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app: server
        version: v1
    spec:
      containers:
      - args:
        - --port
        - "80"
        - --version
        - v1
        image: docker.io/istio/app:1.0.0
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 80
        resources: {}
