apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egressgateway-to-ingressgateway-server-ns2
spec:
  hosts:
  - server.ns2.svc.cluster.global
  gateways:
  - istio-egressgateway-server-ns2
  tls:
  - match:
    - port: 80
      sniHosts:
      - server.ns2.svc.cluster.global
    route:
    - destination:
        host: cluster2-ingress-gateway.service.entry
        port:
          number: 80
